[[main]]
name = "Join WhatsApp Group"
url = "https://chat.whatsapp.com/BZ098mBwOfeKW0IKFFmHlI"
weight = 50
pre = "<img src='/whatsapp-logo.svg' alt='Join Whatsapp Group'>"
target = "_blank"

[[main]]
name = "Holidays"
url = "/files/list-of-holidays-2024.pdf"
weight = 50
target = "_blank"

[[footer]]
name = "DAE Units"
url = "/files/hyperlinks-to-dae-units.pdf"
weight = 50
target = "_blank"
